// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://uutaghaildtlsjistpkz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InV1dGFnaGFpbGR0bHNqaXN0cGt6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ1NjM4NTcsImV4cCI6MjA3MDEzOTg1N30.o7joVU-LUaTE_kAau41R18wWQBhl3TAbu6QsnEGtmf4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});